### ISSUE TITLE
Permissions for Linux build

### ISSUE THREAD

**Issue by aleksrutins** [innov8rz-ftc-team-11039/TeleDrive-2.0#2]
Hello,

I'm looking to get this building for Linux. Many modern Linux packaging systems ([Flatpak](https://flatpak.org), [snapd](https://snapcraft.io), and others) sandbox apps, so that they can't access anything that you don't explicitly tell them to. I'm wondering what sort of permissions this would need. I know it will need network and IPC permissions, so I can start there. I'm not sure what sort of file access it would need, though, other than the log file storage, which can go in the appdata directory (which is available by default).

**Edit:** Just noticed the .deb and .rpm builds, thanks! However, there should still be a cross-distro solution to work on non-Debian and non-Fedora distros (such as Arch, which I use).

**Comment by mihir-chauhan** [comment]
Hi @aleksrutins, the only permissions that are required for TeleDrive are network and file access within that folder.
