### ISSUE TITLE
Consider using electron-builder

### ISSUE THREAD

**Issue by aleksrutins** [innov8rz-ftc-team-11039/TeleDrive-2.0#3]
[electron-builder](https://electron.build) is an alternative to electron-forge that is fully compatible and has better support for Linux. You can see the changes at [my fork](https://github.com/ManchesterMachineMakers/TeleDrive-2.0). It requires no configuration and supports, in addition to all the electron-forge targets, non-broken Snap, Flatpak and AppImage builds.

**Comment by mihir-chauhan** [comment]
Hi @aleksrutins, I haven't tried electron-builder yet, but I will soon. Please let me know if it works for you.
