### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by aleksrutins** [innov8rz-ftc-team-11039/TeleDrive-2.0#4]
I just noticed that the JS code is all in `index.html`, which reminded me of [one of my old projects](https://github.com/aleksrutins/makerbuild) (look back in the commit history). I'm working on some organization for this project in my fork on [the `code-organization` branch](https://github.com/ManchesterMachineMakers/TeleDrive-2.0/tree/code-organization). Please have a look. If this conflicts with any of your plans, feel free to close this issue.

**Comment by mihir-chauhan** [comment]
Hi @aleksrutins, thanks for the improvements, I will merge it here soon.

**Comment by aleksrutins** [comment]
Please note that this repo also has some other stuff in it too, namely `electron-builder` and Nix.

**Comment by mihir-chauhan** [comment]
Thanks, can you please make a pull request? I can then easily merge

**Comment by aleksrutins** [comment]
I have created a PR (#5).
