### ISSUE TITLE
Server coming back up?

### ISSUE THREAD

**Issue by Nv7-GitHub** [innov8rz-ftc-team-11039/TeleDrive-2.0#6]
When will the servers come back up? If not soon, is it possible to host it on my servers?

**Comment by mihir-chauhan** [comment]
Hi @Nv7-GitHub,
I have created a public repository you can find [here](https://github.com/innov8rz-ftc-team-11039/TeleDrive-2.0-Server) which has the server-side code to run TeleDrive. The installation instructions are on the repository's README. Hope this helps!
